<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<!-- head -->

<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <title><?= tplGet('metaTitle'); ?></title>

    <!-- Head Javascripts -->
    <?= tplGet('headJS'); ?>

    <!--General Stylesheets-->
    <?= tplStylesheet('style'); ?>
    <?= tplStylesheets(); ?>

</head>
